import "./index.scss";
import "./js/pages/home";
import "./js/components/header";
import { example } from "./js/utils/constants";
import "swiper/css";
import "swiper/css/bundle";
import "swiper/css/mousewheel";
import "./js/pages/adding";
import "./js/components/main-a";
import "./js/components/lkChangingBlocks";
import "./js/components/baner";
